"""empty message

Revision ID: 1120104cb588
Revises: 9489b96bd96c
Create Date: 2022-08-22 13:17:32.029627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1120104cb588'
down_revision = '9489b96bd96c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=100), nullable=True))
    op.drop_column('user', 'passw')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passw', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=100), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
