"""empty message

Revision ID: 9489b96bd96c
Revises: e34cc4e4de10
Create Date: 2022-08-22 13:16:36.649664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9489b96bd96c'
down_revision = 'e34cc4e4de10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passw', sa.String(length=100), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=20), nullable=True))
    op.drop_column('user', 'passw')
    # ### end Alembic commands ###
